            newObject(desertDML, SimVolume, "desertDML.vol");
            addToSet("MissionGroup\\Volumes", desertDML);
            echo("added desertDML.vol");
            newObject(savanaDML, SimVolume, "savanaDML.vol");
            addToSet("MissionGroup\\Volumes", savanaDML);
            echo("added savanaDML.vol");
            newObject(human1DML, SimVolume, "human1DML.vol");
            addToSet("MissionGroup\\Volumes", human1DML);
            echo("added human1DML.vol");
            newObject(titanDML, SimVolume, "titanDML.vol");
            addToSet("MissionGroup\\Volumes", titanDML);
            echo("added titanDML.vol");
